name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'     
        required: true
        type: string
      tag:
        description: 'Git Tag to checkout'
        required: true
        type: string

jobs:
  release:
    runs-on: macOS-15
    steps:

      - uses: actions/checkout@v3

      - name: Clone libXray at tag
        uses: actions/checkout@v3
        with:
          repository: 'xtls/libXray'
          path: 'xray'
          ref: ${{ github.event.inputs.tag }}

      - name: Clone XrayCore to parent of libXray
        run: |
          git clone https://github.com/XTLS/Xray-core.git Xray-core

      - name: Setup Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: '1.22.4'

      - name: Build xcframework
        run: |
          cd xray
          python3 build/main.py apple gomobile
          cd ..
          mv ./xray/LibXray.xcframework ./XrayKit.xcframework
          zip -ry ./XrayKit.xcframework.zip ./XrayKit.xcframework

      - name: Detect checksum
        run: |
          export TEMP=`shasum -a 256 ./XrayKit.xcframework.zip`
          export CHECKSUM=${TEMP:0:64}
          echo "FILE_CHECKSUM=${CHECKSUM}" >> $GITHUB_ENV
          unset CHECKSUM
          unset TEMP

      - name: Update package file
        run: |
          echo "// swift-tools-version: 5.7" > Package.swift
          echo "" >> Package.swift
          echo "import PackageDescription" >> Package.swift
          echo "" >> Package.swift
          echo "let package = Package(" >> Package.swift
          echo "  name: \"XrayKit\"," >> Package.swift
          echo "  platforms: [.iOS(.v15)]," >> Package.swift
          echo "  products: [" >> Package.swift
          echo "    .library(name: \"XrayKit\", targets: [\"XrayKit\"])" >> Package.swift
          echo "  ]," >> Package.swift
          echo "  targets: [" >> Package.swift
          echo "    .binaryTarget(" >> Package.swift
          echo "      name: \"XrayKit\"," >> Package.swift
          echo "      url: \"https://github.com/byteprovider/XrayKit/releases/download/${{ github.event.inputs.version }}/XrayKit.xcframework.zip\"," >> Package.swift
          echo "      checksum: \"${{ env.FILE_CHECKSUM }}\"" >> Package.swift
          echo "    )" >> Package.swift
          echo "  ]" >> Package.swift
          echo ")" >> Package.swift

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: XrayKit Release ${{ github.event.inputs.version }}
          commit_user_name: Byte Provider
          commit_user_email: contact@byteprovider.app
          tagging_message: ${{ github.event.inputs.version }}
          file_pattern: 'Package.swift'

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          tag_name: ${{ github.event.inputs.version }}
          body: 'Compiled from source tag: ${{ github.event.inputs.tag }}'
          files: ./XrayKit.xcframework.zip
